remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Healing Minds"
description: "Embrace your Mind"
url: "https://github.com/Nyela-10/Nyela_S"
logo: "https://logo-maker.freelogodesign.org/en/logo/edit/f78c281c3ca54682befbbbbc3f1b0cbc"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax:
  enable: true
#  combo: "tex-mml-chtml"
#  tags: "none"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
    
# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Site Author
#author:
  #name: Michael Rose
  #picture: /images/michael-rose-photo.jpg
  #email:
  #twitter: mmistakes
  #links:
   # - title: Twitter
    #  url: https://twitter.com/mmistakes
     # icon: fab fa-twitter-square
    #- title: Instagram
     # url: https://instagram.com/mmistakes
     # icon: fab fa-instagram
    #- title: GitHub
     # url: https://github.com/mmistakes
      #icon: fab fa-github-square

# Footer Links
footer_links:
  - title: GitHub
    url: https://nyela-10.github.io/Nyela_S/
    icon: fab fa-github-square
 
